# yamllint disable-line rule:document-start
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - composer.json
          - composer.lock
          - yarn.lock
          - package.json
