---
name: trellis-rewrite-inventory
description: Rewrite the SSH connection details in a Trellis inventory file
inputs:
  SSH_HOST:
    required: true
  SSH_PORT:
    required: true
  TRELLIS_ENVIRONMENT:
    required: true
  HOSTS_FILE:
    required: true
runs:
  using: composite
  steps:
    - id: run
      shell: bash
      run: bash "${{ github.action_path }}/run.sh"
      env:
        INPUT_SSH_HOST: ${{ inputs.SSH_HOST }}
        INPUT_SSH_PORT: ${{ inputs.SSH_PORT }}
        INPUT_TRELLIS_ENVIRONMENT: ${{ inputs.TRELLIS_ENVIRONMENT }}
        INPUT_HOSTS_FILE: ${{ inputs.HOSTS_FILE }}
